apiVersion: v1
kind: Service 
metadata:
  name: django-nginx-srv
spec:
   selector:
      app: crud
   type: LoadBalancer
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30000
