apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-demo
spec:
   replicas: 3
   selector:
    matchLabels:
      app: demo
      tier: frontend
      track: stable
   template:
    metadata:
      labels:
        app: demo
        tier: frontend
        track: stable
    spec:
      containers:
      - name: app-nginx
        image: gerrome/djangoapp_nginx:1
