apiVersion: v1
kind: Service 
metadata:
  name: demo-service
spec:
   selector:
      app: demo
   type: LoadBalancer
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30000
