apiVersion: v1
kind: Service 
metadata:
  name: service-dr
  namespace: drp
spec:
   selector:
      app: dr
   type: LoadBalancer
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30000
