apiVersion: apps/v1
kind: Deployment 
metadata:
  name: django-react
  namespace: django-react-postgres
spec:
   replicas: 3
   selector:
    matchLabels:
      app: dr
      tier: backend
      track: stable
   template:
    metadata:
      labels:
        app: dr
        tier: backend
        track: stable
    spec:
      containers:
      - name: app-django
        image: gerrome/django-react2_backend:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      #- name: app-nginx
      #  image: gerrome/crud-vuejs-django_nginx:1.0
      #  ports:
      #  - containerPort: 80
